### ISSUE TITLE
multiple images

### ISSUE THREAD

**Issue by ghost** [trev/Rotatable#3]
would be great to bind using a class, have tried and rotate binds strangely.  Great work by the way have it on touch screen 22inch monitor with my photos looks awesome.

**Comment by suryanaga** [comment]
+1 on this. Works great with 1 element but as soon as you bring multiple elements in the mix this code doesn't work :(

**Comment by trev** [comment]
Hey guys, I've actually completely rewritten this plugin and made it much tidier. I'll be updating the master very shortly.
@sanjaypoyzer Thanks for your [PR](https://github.com/trev/Rotatable/pull/4), but I've already fixed the issue in the new version. (merged it anyways, cause it's cool)
